name: Deploy on Push

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2
        with:

          ARGS: '-rlgoDzvc --delete'
          SOURCE: '.'
          TARGET: './'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: '22'
          SCRIPT_BEFORE: ls