name: Deploy on Push

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Info
        run: |
          echo "Debug Info:"
          echo "Current directory: $(pwd)"
          echo "List files: $(ls -al)"

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2
        with:

          ARGS: '-rlgoDzvc -i --delete'
          SOURCE: '.'
          TARGET: '.'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: 'root'
          REMOTE_HOST: '154.56.43.14'
          REMOTE_PORT: '22'

